-- Love Empire · 0006 · 圖鑑擴充 17 → 80 張
-- memory_cards FK 到 card_catalog — 新卡要先塞 catalog 才能 insert memory_cards

insert into card_catalog (id, name, rarity, theme, emoji) values
  -- daily 日常 (擴充)
  ('c20', '早餐鮪魚吐司', 'N',  'daily',   '🍞'),
  ('c21', '外送夜消',     'N',  'daily',   '🍜'),
  ('c22', '一起逛超市',   'N',  'daily',   '🛒'),
  ('c23', '洗衣晾衣',     'N',  'daily',   '🧺'),
  ('c24', '一起倒垃圾',   'N',  'daily',   '🗑️'),
  ('c25', '沙發電影夜',   'N',  'daily',   '🎬'),
  ('c26', '一起賴床',     'N',  'daily',   '🛌'),
  ('c27', '夜市小吃',     'R',  'daily',   '🍢'),
  ('c28', '手牽手散步',   'N',  'daily',   '🤝'),
  ('c29', '一起晨跑',     'R',  'daily',   '🏃'),
  ('c30', '整理房間',     'N',  'daily',   '🧹'),
  ('c31', '共用耳機',     'N',  'daily',   '🎧'),
  ('c32', '洗頭幫吹髮',   'R',  'daily',   '💇'),
  ('c33', '一起泡澡',     'SR', 'daily',   '🛁'),
  ('c34', '新家第一夜',   'SR', 'daily',   '🏠'),
  ('c35', '一起追劇',     'N',  'daily',   '📺'),
  ('c36', '睡前晚安',     'N',  'daily',   '🌙'),

  -- romance 浪漫 (擴充)
  ('c40', '第一個吻',     'SSR', 'romance', '💋'),
  ('c41', '一起看星空',   'SR',  'romance', '⭐'),
  ('c42', '摩天輪夜景',   'SR',  'romance', '🎡'),
  ('c43', '手寫情書',     'R',   'romance', '💌'),
  ('c44', '燭光晚餐',     'SR',  'romance', '🕯️'),
  ('c45', '送花告白',     'R',   'romance', '💐'),
  ('c46', '雨中擁吻',     'SR',  'romance', '☔'),
  ('c47', '月下散步',     'R',   'romance', '🌕'),
  ('c48', '海邊散步',     'R',   'romance', '🏖️'),
  ('c49', '一起賞櫻',     'SR',  'romance', '🌸'),
  ('c50', '情人節花束',   'R',   'romance', '🌹'),
  ('c51', '共乘機車',     'N',   'romance', '🏍️'),
  ('c52', '耳邊低語',     'N',   'romance', '🗣️'),
  ('c53', '深情擁抱',     'R',   'romance', '🫂'),
  ('c54', '含淚和好',     'SR',  'romance', '🥺'),
  ('c55', '十指緊扣',     'N',   'romance', '✋'),
  ('c56', '靠肩睡著',     'N',   'romance', '💤'),
  ('c57', '突然的驚喜',   'R',   'romance', '🎁'),
  ('c58', '牽手入睡',     'R',   'romance', '🤲'),

  -- travel 旅行 (擴充)
  ('c60', '沖繩海邊',     'SR',  'travel',  '🏝️'),
  ('c61', '北海道雪景',   'SR',  'travel',  '🗻'),
  ('c62', '峇里島日落',   'SSR', 'travel',  '🌅'),
  ('c63', '台南古城遊',   'R',   'travel',  '🏛️'),
  ('c64', '墾丁浪花',     'R',   'travel',  '🌊'),
  ('c65', '九份山城',     'R',   'travel',  '⛰️'),
  ('c66', '東京鐵塔',     'SR',  'travel',  '🗼'),
  ('c67', '首爾賞櫻',     'SR',  'travel',  '🌸'),
  ('c68', '香港夜景',     'R',   'travel',  '🌃'),
  ('c69', '曼谷夜市',     'R',   'travel',  '🍢'),
  ('c70', '自駕環島',     'SR',  'travel',  '🚗'),
  ('c71', '露營看星空',   'SR',  'travel',  '🏕️'),
  ('c72', '溫泉之旅',     'R',   'travel',  '♨️'),
  ('c73', '海外蜜月',     'SSR', 'travel',  '✈️'),

  -- festival 節日限定 (擴充)
  ('c80', '七夕鵲橋',     'SR',  'festival', '🌠'),
  ('c81', '白色情人節',   'SR',  'festival', '🤍'),
  ('c82', '萬聖節裝扮',   'R',   'festival', '🎃'),
  ('c83', '端午粽情',     'R',   'festival', '🥟'),
  ('c84', '跨年倒數',     'SR',  'festival', '🎊'),
  ('c85', '元宵燈會',     'R',   'festival', '🏮'),
  ('c86', '母親節伴偕',   'R',   'festival', '💐'),
  ('c87', '父親節陪伴',   'R',   'festival', '👔'),
  ('c88', '國慶煙火',     'R',   'festival', '🎇'),
  ('c89', '冬至湯圓',     'R',   'festival', '🍡'),
  ('c90', '愚人節玩笑',   'N',   'festival', '🎭'),
  ('c91', '清明追思',     'N',   'festival', '🌿'),
  ('c92', '秋分賞菊',     'N',   'festival', '🌼')
on conflict (id) do nothing;
